config/routes.rb
Rails.application.routes.draw do
  resources :boards
  root 'boards#index'

  # 一覧取得
  get 'boards' => 'boards#index'
  # 新規作成
  post 'boards' => 'boards#create'
  # 記事編集
  get 'boards/:id/edit' => 'boards#edit'
  # 記事更新
  patch 'boards/:id' => 'boards#update'
  # 記事削除
  delete 'boards/:id' => 'boards#destory'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # primary_abstract_class
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/testdb.rb
class Testdb < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def hello
      render html: "hello, world!"
    end
  end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all.order(id: 'asc')
  end

  # 新規作成
  def new
    @board = Board.new
  end

  def create
    @board = Board.create(board_params)
    redirect_to boards_path
  end

  # 編集
  def edit
    @board = Board.find(params[:id])
  end

  # 更新
  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    redirect_to boards_path
  end

  # 削除
  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  # パラメータ定義
  private
    # permitで、フォームで設定している値を設定
    def board_params
      params.require(:board).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
  def item
  end
  def register
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def user_create
  end
end

app/controllers/testdbs_controller.rb
class TestdbsController < ApplicationController
    def index
        # @testdbs = Testdb.find(1)だと1行目のデータのみ取得
        @testdbs = Testdb.all
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def user_create
    Post.create(:content => params[:content])
    redirect_to("/posts")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/testdb_helper.rb
module TestdbHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/boards/edit.html.erb
<h1>ボード編集</h1>
<%= form_with(model: @board, url: "/boards/#{@board.id}", method: :patch) do |f| %>
  <%# nameの項目 %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%# descriptionの項目 %>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%# 登録ボタン %>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', boards_path %>

app/views/boards/index.html.erb
<h1>ボード一覧</h1>
<table>
  <thead>
    <tr>
      <th>ボード名</th>
    </tr>
  </thead>
  <tbody>
  <% @boards.each do |board| %>
    <tr>
      <td>Name：<%= board.name %></td>
      <td>説明：<%= board.description %></td>
      <td><%= link_to '編集', edit_board_path(board) %></td>
      <%# method: delete を使用する場合、rails-ujs などを使用するか、button_to で代替え, link_to を使用するならば GET %>
      <td><%= button_to '削除', "/boards/#{board.id}", :method => :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h2>ボードの追加</h2>
<%= form_with model: @board do |f| %>
  <%# nameの項目 %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%# descriptionの項目 %>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%# 登録ボタン %>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', boards_path %>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/home/index.html.erb
index

app/views/home/item.html.erb
aaa

app/views/home/register.html.erb
<h1>DB登録テスト</h1>
<%= form_tag("/user_create") do %>
<p>投稿内容</p>
<input type="text" name="content"></input>
<button type="submit">登録</button>
<% end %>

app/views/home/top.html.erb
<h1>Hello,World!</h1>
<p>
    <a href="https://tsudoi.org/guide/">吉本式BEM設計</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- header -->
  <head>
  <title>AppName</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  </head><!-- /header -->

  <!-- menu -->
  <div class="menu">
    <ul class="menu-list">
    <li class="menu-item"><%= link_to("top", "/top") %></li>
    <li class="menu-item"><%= link_to("about", "/about") %></li>
    <li class="menu-item"><%= link_to("posts", "/posts") %></li>
    <li class="menu-item"><%= link_to("送信フォーム", "/home/register") %></li>
    <li class="menu-item"><%= link_to("test", "/test") %></li>
    </ul>
  </div><!-- /menu -->

  <body>
  <!-- main -->  
  <div class="main">
  <!-- gnav -->
  <nav class ="gnav">
  </nav><!-- /gnav -->

  <%= yield %>
  </div><!-- /main -->
  </body>

  <!-- footer -->
  <footer>
  </footer><!-- /footer -->

</html>

app/views/layouts/boards.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render 'layouts/common/header' %>

  <body>
    <%= yield %>
  </body>

  <%= render 'layouts/common/footer' %>

</html>

app/views/layouts/common/_footer.html.erb
<%= link_to 'ボード追加 - foot', new_board_path %>

app/views/layouts/common/_header.html.erb
<%= link_to 'ボード追加', new_board_path %>

app/views/posts/index.html.erb
<div class="posts">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-item">
        <%= post.id %>
        <%= post.content %>
      </div>
    <% end %>
  </div>
</div>

app/views/testdbs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% @testdbs.each do |testdb| %>
    <%= testdb.uuid %>
    <%= testdb.name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>